//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvc1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public bool course { get; set; }
        public string Country { get; set; }
        public bool course2 { get; set; }
        public bool course3 { get; set; }

        public bool course4 { get; set; }
    }
}
